# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: CPSLAB
email: iwailab2017@cps.im.dendai.ac.jp
description: > # this means to ignore newlines until "baseurl:"
    TDU CPSLAB
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
# vtwitter_username: jekyllrb
github_username:  cpslab

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

# navigation
navigations:
  -
    href: /sesearch
    key: sesearch
    label: Research
  -
    href: /4student
    key: 4student
    label: 4Student
  -
    href: /works
    key: works
    label: Works
  -
    href: /members
    key: members
    label: Members
  -
    href: /blog
    label: Blog
  -
    href: /downloads
    key: downloads
    label: Downloads
  -
    href: /contact
    key: contact
    label: Contact
#  -
#    href: https://github.com/findById
#    label: GitHub
#    target: _blank
